title: The Missing Semester of Your ML Education
author: ""
copyright: "2026"

only_build_toc_files: true

execute:
  execute_notebooks: "off"

repository:
  url: https://github.com/georgerpu/missing-semester-ml
  path_to_book: .
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
  extra_css:
    - _static/custom.css
  extra_navbar: ""

sphinx:
  config:
    html_theme_options:
      repository_url: https://github.com/georgerpu/missing-semester-ml
      use_repository_button: true
      use_issues_button: true
      home_page_in_toc: true
      show_navbar_depth: 1
      logo:
        text: "Missing Semester ML"
